apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "dir-appset"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - merge:
        mergeKeys:
          - appName
        generators:
          - list:
              elements:
                - appName: spire-crds
                  namespace: spire-crds
                  syncWave: "0"
                - appName: spire
                  namespace: spire
                  syncWave: "1"
                - appName: dir
                  namespace: dir
                  syncWave: "2"
                - appName: dirctl
                  namespace: dirctl
                  syncWave: "3"
          - matrix:
              generators:
                - list:
                    elements:
                      - appName: spire-crds
                      - appName: spire
                      - appName: dir
                      - appName: dirctl
                - git:
                    repoURL: "https://github.com/ramizpolic/dir-deploy"
                    revision: main
                    files:
                      - path: "clusters/dir/cluster-config.json"
          - matrix:
              generators:
                - list:
                    elements:
                      - appName: spire-crds
                      - appName: spire
                      - appName: dir
                      - appName: dirctl
                - git:
                    repoURL: "https://github.com/ramizpolic/dir-deploy"
                    revision: main
                    files:
                      - path: "applications/{{ appName }}/config.json"
  template:
    metadata:
      name: "dir-appset-{{ appName }}"
      labels:
        app: "{{ appName }}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{ syncWave }}"
    spec:
      project: "dir"
      sources:
        - repoURL: "{{ chart_repo }}"
          chart: "{{ chart_name }}"
          targetRevision: "{{ chart_version }}"
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - "$values/applications/{{ appName }}/values.yaml"
        - repoURL: "https://github.com/ramizpolic/dir-deploy"
          targetRevision: main
          ref: values
      destination:
        server: "{{ cluster_address }}"
        namespace: "{{ namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true
          - RespectIgnoreDifferences=true
