apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "multi-component-dev-appset"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - merge:
        mergeKeys:
          - appName
        generators:
          - list:
              elements:
                - appName: spire-crds
                  namespace: spire-crds
                  syncWave: "0"
                - appName: spire
                  namespace: spire
                  syncWave: "1"
                - appName: dir
                  namespace: dir-dev
                  syncWave: "2"
          - matrix:
              generators:
                - list:
                    elements:
                      - appName: spire-crds
                      - appName: spire
                      - appName: dir
                - git:
                    repoURL: "https://github.com/ramizpolic/dir-deploy"
                    revision: main
                    files:
                      - path: "clusters/dir/dev/cluster-config.json"
          - matrix:
              generators:
                - list:
                    elements:
                      - appName: spire-crds
                      - appName: spire
                      - appName: dir
                - git:
                    repoURL: "https://github.com/ramizpolic/dir-deploy"
                    revision: main
                    files:
                      - path: "applications/{{ appName }}/dev/config.json"
  template:
    metadata:
      name: "dir-dev-{{ appName }}-argoapp"
      labels:
        env: "dev"
        app: "{{ appName }}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{ syncWave }}"
    spec:
      project: "dir-dev"
      sources:
        - repoURL: "{{ chart_repo }}"
          chart: "{{ chart_name }}"
          targetRevision: "{{ chart_version }}"
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - "$values/applications/{{ appName }}/dev/values.yaml"
        - repoURL: "https://github.com/ramizpolic/dir-deploy"
          targetRevision: main
          ref: values
      destination:
        server: "{{ cluster_address }}"
        namespace: "{{ namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
