apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "dir-dev-appset"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    ## Use merge generator to merge the configurations from different sources into a single object
    - merge:
        mergeKeys:
          - values.selector
          - values.appName
        generators:
          ## Application Charts
          - git:
              repoURL: "https://github.com/ramizpolic/dir-deploy"
              revision: main
              files:
                - path: "applications/dir/dev/**/config.json"
              values:
                selector: "{{ path.basename }}"
                appName: "dir"
          - git:
              repoURL: "https://github.com/ramizpolic/dir-deploy"
              revision: main
              files:
                - path: "applications/spire/dev/**/config.json"
              values:
                selector: "{{ path.basename }}"
                appName: "spire"
          - git:
              repoURL: "https://github.com/ramizpolic/dir-deploy"
              revision: main
              files:
                - path: "applications/spire-crds/dev/**/config.json"
              values:
                selector: "{{ path.basename }}"
                appName: "spire-crds"
          ## Cluster Configurations
          - git:
              repoURL: "https://github.com/ramizpolic/dir-deploy"
              revision: main
              files:
                - path: "clusters/dir/dev/**/cluster-config.json"
              values:
                selector: "{{ path.basename }}"
                appName: "dir"
          - git:
              repoURL: "https://github.com/ramizpolic/dir-deploy"
              revision: main
              files:
                - path: "clusters/dir/dev/**/cluster-config.json"
              values:
                selector: "{{ path.basename }}"
                appName: "spire"
          - git:
              repoURL: "https://github.com/ramizpolic/dir-deploy"
              revision: main
              files:
                - path: "clusters/dir/dev/**/cluster-config.json"
              values:
                selector: "{{ path.basename }}"
                appName: "spire-crds"
  template:
    metadata:
      name: "{{ values.selector }}-{{ values.appName }}-dev-argoapp"
      labels:
        cloud: "{{ values.selector }}"
        env: "dev"
        app: "{{ values.appName }}"
    spec:
      project: "dir-dev"
      sources:
        - repoURL: "{{chart_repo}}"
          chart: "{{chart_name}}"
          targetRevision: "{{ chart_version }}"
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - "$values/applications/{{ values.appName }}/dev/{{ values.selector }}/values.yaml"
        - repoURL: "https://github.com/ramizpolic/dir-deploy"
          targetRevision: main
          ref: values
      destination:
        server: "{{ cluster_address }}"
        namespace: "{{ namespace }}"
      syncPolicy:
        automated:
          prune: false
        syncOptions:
          - CreateNamespace=true
