apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "multi-component-dev-appset"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys:
          - appName
        generators:
          - list:
              elements:
                - appName: dir
                  namespace: dir-dev
                - appName: spire
                  namespace: spire
                - appName: spire-crds
                  namespace: spire-crds
          - git:
              repoURL: "https://github.com/ramizpolic/dir-deploy"
              revision: main
              files:
                - path: "clusters/dir/dev/cluster-config.json"
          - git:
              repoURL: "https://github.com/ramizpolic/dir-deploy"
              revision: main
              files:
                - path: "applications/{{ appName }}/dev/config.json"
  template:
    metadata:
      name: "{{ appName }}-dev-argoapp"
      labels:
        env: "dev"
        app: "{{ appName }}"
    spec:
      project: "dir-dev"
      sources:
        - repoURL: "{{ chart_repo }}"
          chart: "{{ chart_name }}"
          targetRevision: "{{ chart_version }}"
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - "$values/applications/{{ appName }}/dev/values.yaml"
        - repoURL: "https://github.com/ramizpolic/dir-deploy"
          targetRevision: main
          ref: values
      destination:
        server: "{{ cluster_address }}"
        namespace: "{{ namespace }}"
      syncPolicy:
        automated:
          prune: false
        syncOptions:
          - CreateNamespace=true
