apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "dir-prod-appset"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - merge:
        mergeKeys:
          - appName
        generators:
          - list:
              elements:
                - appName: spire-crds
                  namespace: dir-prod-spire-crds
                  syncWave: "0"
                - appName: spire
                  namespace: dir-prod-spire
                  syncWave: "1"
                - appName: dir
                  namespace: dir-prod-dir
                  syncWave: "2"
                - appName: dir-admin
                  namespace: dir-prod-dir-admin
                  syncWave: "3"
          # Get cluster config to set the cluster address
          - matrix:
              generators:
                - list:
                    elements:
                      - appName: spire-crds
                      - appName: spire
                      - appName: dir
                      - appName: dir-admin
                - git:
                    repoURL: "https://github.com/ramizpolic/dir-deploy"
                    revision: main
                    files:
                      - path: "clusters/dir/prod/a/cluster-config.json"
          # Get app config to set chart details
          - matrix:
              generators:
                - list:
                    elements:
                      - appName: spire-crds
                      - appName: spire
                      - appName: dir
                      - appName: dir-admin
                - git:
                    repoURL: "https://github.com/ramizpolic/dir-deploy"
                    revision: main
                    files:
                      - path: "applications/{{ appName }}/prod/config.json"
  template:
    metadata:
      name: "{{ appName }}-dir-prod-argoapp"
      labels:
        app: "{{ appName }}"
        env: "prod"
      annotations:
        argocd.argoproj.io/sync-wave: "{{ syncWave }}"
    spec:
      project: "dir-prod"
      sources:
        - repoURL: "{{ chart_repo }}"
          chart: "{{ chart_name }}"
          targetRevision: "{{ chart_version }}"
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              # Default values file
              - "$values/applications/{{ appName }}/prod/values.yaml"
              # Generated values file, usually created by scripts
              - "$values/applications/{{ appName }}/prod/gen.values.yaml"
        - repoURL: "https://github.com/ramizpolic/dir-deploy"
          targetRevision: main
          ref: values
      destination:
        server: "{{ cluster_address }}"
        namespace: "{{ namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true
          - RespectIgnoreDifferences=true
